# -*- coding: utf-8 -*-
"""topic_definitions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTfmjhwIG4Ghvjkwrgwu5pEBw3SW16Bc
"""

import pandas as pd

df = pd.read_csv("/content/data/topics_definitions.csv")

df.head(3)